# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: 'New York Bagel Cafe'
email: nybcafe@gmail.com
description: >
  The New York Bagel Cafe is one of those cozy<br/>
  bistros you are always delighted to find.<br/>
  Leisurely Viennese style dining offers quiet elegance,<br/>
  good value, and excellent food.<br/>
baseurl: '' # the subpath of your site, e.g. /blog
url: '' # the base hostname & protocol for your site, e.g. http://example.com

address:
  - {street: "8430 Gateway Blvd", city: "Edmonton", province: "AB", postal_code: "T6E-4B4"}

operations:
  - {day: 'Monday-Friday', hours: '8:00 AM - 4:00 PM'}
  - {day: "Saturday", hours: '8:00 AM - 4:00 PM' }
  - {day: 'Sunday', hours: '8:00 AM - 4:00 PM' }

# SEO
#image: /assets/images/open_graph_image.png
google_analytics: # UA-XXXXXXXX-XX -> https://minimalanalytics.com/

# Build settings
markdown: kramdown
incremental: true
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - flightdeck.manifest.js
  - Gemfile
  - Gemfile.lock
  - gulp_tasks
  - gulpfile.js
  - LICENSE
  - node_modules
  - npm-debug.log
  - package-lock.json # for those that use npm
  - package.json
  - README.md
  - vendor
  - yarn.lock # for those that use yarn
